configured_endpoints: 31
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/aymara%2Faymara-sdk-d950d722e230f3047d1a18717eecdf71aa487d8b565c5b35daa7eb2a95c0a763.yml
openapi_spec_hash: 3bacbb36eadb2142baead7f9b210f33e
config_hash: 8c66f567d5fccb50fc74ef32567eaeed
